# Generated by Django 5.1.6 on 2025-02-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='user',
            name='verification',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
