# Generated by Django 5.1.6 on 2025-02-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_verification_code_user_verification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verification',
            new_name='verification_code',
        ),
    ]
