# Generated by Django 5.1.6 on 2025-02-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hello'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
