# Generated by Django 5.1.6 on 2025-03-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
