# Generated by Django 5.1.6 on 2025-02-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='created_by',
        ),
    ]
