# Generated by Django 5.1.6 on 2025-02-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_portal', '0005_answer_additional_data_answer_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='additional_data',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
