# Generated by Django 5.1.6 on 2025-02-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_portal', '0008_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='created_by',
        ),
        migrations.AddField(
            model_name='answer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
