# Generated by Django 5.1.6 on 2025-02-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_portal', '0009_remove_answer_created_by_answer_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='points',
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
