# Generated by Django 5.1.6 on 2025-03-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_portal', '0015_testattempt_studentresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='isactive',
            field=models.BooleanField(default=False),
        ),
    ]
