# Generated by Django 5.1.6 on 2025-03-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_portal', '0016_test_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testactive', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='isactive',
        ),
    ]
