# Generated by Django 5.1.6 on 2025-03-10 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_portal', '0017_testactive_remove_test_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='testactive',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_portal.test'),
        ),
    ]
