# Generated by Django 5.1.6 on 2025-03-10 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_portal', '0020_delete_testactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_portal.test')),
            ],
        ),
    ]
