# Generated by Django 5.1.6 on 2025-03-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_portal', '0021_testactive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestActive',
        ),
    ]
