# Generated by Django 5.1.6 on 2025-03-10 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_portal', '0022_delete_testactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_status', to='test_portal.test')),
            ],
        ),
    ]
