# Generated by Django 5.1.6 on 2025-03-11 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_portal', '0023_testactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('fixed', 'Fixed Order'), ('shuffle', 'Shuffle Questions & Answers')], default='fixed', max_length=10)),
                ('questions_per_page', models.IntegerField(default=5)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_set', to='test_portal.test')),
            ],
        ),
    ]
