# Generated by Django 5.1.6 on 2025-03-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_portal', '0025_studenttestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='marks_awarded',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
